import { test, expect } from '@playwright/test';

test('Verify Retirement Projector Calculator', async ({ page }) => {
  await page.goto('https://www.mlc.com.au/');
  await page.getByRole('link', { name: 'Advice & tools' }).click();
  await page.getByRole('menuitem', { name: 'Tools & calculators' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('[id="_content_mlc_en_personal_advice_tools-and-calculators_jcr_content_par-col-body-2_bootstrap_row_copy_col2"]').getByRole('link', { name: 'Start' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('heading', { name: 'Retirement Projector' }).click();
  await page1.getByText('I accept the assumptions &').click();
  await page1.getByRole('button', { name: 'Get your projection' }).click();
  await page1.getByRole('textbox', { name: 'My age is' }).click();
  await page1.getByRole('textbox', { name: 'My age is' }).fill('35');
  await page1.getByRole('textbox', { name: 'I earn' }).click();
  await page1.getByRole('textbox', { name: 'I earn' }).fill('$50,0000');
  await page1.getByRole('textbox', { name: 'My current super balance is' }).click();
  await page1.getByRole('textbox', { name: 'My current super balance is' }).fill('$20,0000');
  await page1.getByRole('textbox', { name: 'I\'d like to retire at age' }).click();
  await page1.getByRole('textbox', { name: 'I\'d like to retire at age' }).fill('70');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByLabel('I\'d like my super to').selectOption('0');
  await page1.getByRole('textbox', { name: 'Retirement income amount' }).click();
  await page1.getByRole('textbox', { name: 'Retirement income amount' }).fill('$6,0000');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByText('Yes').click();
  await page1.getByLabel('When I retire I\'d like to').selectOption('DEBT');
  await page1.getByRole('textbox', { name: 'Amount' }).click();
  await page1.getByRole('textbox', { name: 'Amount' }).fill('$15,0000');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByText('Yes').click();
  await page1.getByLabel('Do you plan to own your home').getByText('Yes').click();
  await page1.getByRole('textbox', { name: 'Rental income' }).click();
  await page1.getByRole('textbox', { name: 'Rental income' }).fill('$1,0000');
  await page1.getByRole('textbox', { name: 'Bank accounts' }).click();
  await page1.getByRole('textbox', { name: 'Bank accounts' }).fill('$5,0000');
  await page1.getByRole('textbox', { name: 'Term deposits & shares' }).click();
  await page1.getByRole('textbox', { name: 'Term deposits & shares' }).fill('$1,0000');
  await page1.getByRole('textbox', { name: 'Account based pension' }).click();
  await page1.getByRole('textbox', { name: 'Account based pension' }).fill('$1000');
  await page1.getByRole('textbox', { name: 'Other' }).nth(1).click();
  await page1.getByRole('textbox', { name: 'Other' }).nth(1).fill('$500');
  await page1.getByRole('textbox', { name: 'Household contents' }).click();
  await page1.getByRole('textbox', { name: 'Household contents' }).click();
  await page1.getByRole('textbox', { name: 'Household contents' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Household contents' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Household contents' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Household contents' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Household contents' }).fill('$20,000');
  await page1.getByRole('textbox', { name: 'Car, Boat, Caravan' }).click();
  await page1.getByRole('textbox', { name: 'Car, Boat, Caravan' }).fill('$2,0000');
  await page1.getByRole('textbox', { name: 'Investment property' }).click();
  await page1.getByRole('textbox', { name: 'Investment property' }).fill('$19,0000');
  await page1.getByRole('textbox', { name: 'Other' }).nth(2).click();
  await page1.getByRole('textbox', { name: 'Other' }).nth(2).fill('$5000');
  await page1.getByRole('button', { name: 'Calculate Age Pension' }).click();
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByRole('heading', { name: 'Retirement projection' }).click();
  await page1.getByLabel('graph type').selectOption('income');
  await page1.getByRole('button', { name: 'Exit' }).click();
});